### ISSUE TITLE
CrossDefense.start()

### ISSUE THREAD

**Issue by audreylemeur** [Team-4536/FRC4536-2016-Robot#75]
Make CrossDefense not start in enum/autochooser

**Comment by AnonymousAnion** [comment]
I don't think this is an issue in itself because it works, but we should discuss as team how we want to structure autonomous chooser and crossDefense to improve them. Sorry for any confusion this caused, I will create a new issue to address this.

![image](https://cloud.githubusercontent.com/assets/10052290/13437309/2c3771e2-dfa9-11e5-8122-a364ec893e07.png)
